language: perl
perl:
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
  - cpanm --quiet --notest --with-develop --installdeps .
  - cover -delete 

script:
  - perl Build.PL 
  - ./Build build 
  - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,inc" PERL5LIB="lib" prove t/

after_success:
  - cover -report coveralls

